#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# (C) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ----------------------------------------------------------------------------

# Script to create, update and close milestones in multiple GitHub repositories
# Requires GitHub CLI: https://cli.github.com/ and Admin privileges to the repos

set -euo pipefail

usage() {
  cat <<EOF
Usage: ${0##*/} -t <title> [options]
  -t <title>       Title of milestone to be created, updated or closed.
  -c               Close milestone. Otherwise will create a new milestone or
                   update an existing milestone.
  -d <due on>      Milestone due date. Format: YYYY-MM-DDTHH:MM:SSZ
  -p <description> Description of the milestone
  -n               Dry Run, print actions without making changes
  -h, --help       Show this help message

Examples:
  # Create a new milestone
  ${0##*/} -t <title> [-d YYYY-MM-DDTHH:MM:SSZ] [-p <description>]

  # Update all milestones with a new date
  ${0##*/} -t <title> -d <YYYY-MM-DDTHH:MM:SSZ>

  # Close a milestone
  ${0##*/} -t <title> -c
EOF
  exit 1
}

# -- Defaults
STATE="open"
TITLE=""
DUE=""
DESC=""
DRY_RUN=0

# -- Parse options
while getopts "t:d:p:cnh-:" opt; do
  case $opt in
    t) TITLE="$OPTARG" ;;
    c) STATE="closed" ;;
    d) DUE="$OPTARG" ;;
    p) DESC="$OPTARG" ;;
    n) DRY_RUN=1 ;;
    h) usage ;;
    -) [ "$OPTARG" = "help" ] && usage ;;
    *) usage ;;
  esac
done

# -- Modify milestones in relevant repositories
repos=(
#  "MetOffice/um"
#  "MetOffice/jules"
#  "MetOffice/lfric_apps"
#  "MetOffice/lfric_core"
#  "MetOffice/ukca"
#  "MetOffice/casim"
#  "MetOffice/socrates"
#  "MetOffice/um_doc"
#  "MetOffice/simulation-systems"
#  "MetOffice/SimSys_Scripts"
  "MetOffice/git_playground"
)
#
# -- Helper functions
get_milestone_number(){
  local repo_name="$1"
  gh api /repos/"${repo_name}"/milestones --jq ".[] | select(.title == \"${TITLE}\") | .number"
}

run_gh_api(){
  local method="$1"
  local endpoint="$2"
  shift 2
  local -a api_args=("$@")

  if (( DRY_RUN )); then
    echo "[DRY RUN] gh api --method ${method} ${endpoint} ${api_args[*]}"
    return 0
  fi

  gh api --method "${method}" "${endpoint}" "${api_args[@]}" > /dev/null
}


# -- Change milestone for each repository

for repo in "${repos[@]}"; do
  echo "Processing milestone in repository: $repo"


  # -- If milestone exists then fetch the number
  NUMBER=$(get_milestone_number "${repo}")
  if (( NUMBER )); then
    echo "${TITLE} in ${repo} is milestone ${NUMBER}"
  else
    echo "Milestone does not exist in ${repo}"
  fi

  # -- Build GH command from optional arguments.
  gh_args=(-f "title=\"${TITLE}\"")
  [[ -n "$DUE" ]] && gh_args+=(-f "due_on=${DUE}")
  [[ -n "$DESC" ]] && gh_args+=(-f "description=\"${DESC}\"")


  # -- Create or update the milestone
  if [[ "$STATE" == "open" ]]; then

    if (( NUMBER )); then
      echo "Updating milestone"
      run_gh_api PATCH "/repos/${repo}/milestones/${NUMBER}" "${gh_args[@]}"
    else
      echo "Creating new milestone"
      run_gh_api POST "/repos/${repo}/milestones" "${gh_args[@]}"
    fi

  # -- Close the milestone
  else

    if (( NUMBER )); then
      echo "Closing milestone #${NUMBER}"
      gh_args+=(-f "state=closed")
      run_gh_api PATCH "/repos/${repo}/milestones/${NUMBER}" "${gh_args[@]}"
    fi
  fi

done
