# -----------------------------------------------------------------------------
# (C) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# -----------------------------------------------------------------------------

# Check Contributor Licence Agreement

name: Legal

on:
  pull_request_target:

concurrency:
  # Automatically cancels the workflow run instantly before the
  # engine can parse empty jobs and generate notification emails
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event.pull_request.head.repo.full_name != 'MetOffice/SimSys_Scripts' }}

permissions: {}

jobs:
  cla:
    uses: MetOffice/growss/.github/workflows/cla-check.yaml@0f9ffe6a138ae9943053621916a850a075997db8 # v1.0.0
    permissions:
      contents: read  # Required to evaluate the event trigger metadata safely
      pull-requests: write  # Required for the downstream engine to post status comments on the PR
