# -----------------------------------------------------------------------------
# (C) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# -----------------------------------------------------------------------------

name: Trigger Review Project

on:
  pull_request_target:
    types: ["opened", "synchronize", "reopened", "edited", "review_requested", "review_request_removed", "closed"]
  pull_request_review:
  pull_request_review_comment:

permissions:
  contents: read  # Required to evaluate the event trigger metadata safely

jobs:
  trigger_project_workflow:
    if: github.repository == 'MetOffice/SimSys_Scripts'

    permissions:
      actions: read  # Required to check out code or parse files safely
      contents: read  # Required to read the upstream triggered workflow run artifact status
      pull-requests: write  # Required for the downstream engine to add comments or update metadata on the PR
    uses: MetOffice/growss/.github/workflows/trigger-project-workflow.yaml@0f9ffe6a138ae9943053621916a850a075997db8 # v1.0.0
